---
title: "DRUG-seq data analysis pipeline"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r}

suppressPackageStartupMessages({
  library(dplyr); library(tidyr); library(limma); library(edgeR)
})
```


```{r}
library(stringr)
library(DT)
library(tidyr)
library(dplyr)
library(foreach)
library(limma)
library(edgeR)
library(umap)
library(data.table)
library(ggplot2)
library(GGally)
library(plotly)
library(ggrepel)
library(viridis)
library(RANN)
library(igraph)
library(RColorBrewer)
library(patchwork)
```

# DRUGseq data analysis pipeline - DMSO selection 

## data path setup
```{r setup,include=FALSE}
dir <- "/Users/liuxin/macpie_Dev/"
setwd(paste0(dir,"/DRUGseqData/DRUG-seq-main"))
analysis_dir <- getwd()
# dataset <- "flowcell_4000_UMI_decode_VH02001612.RData"
input_data_dir <- file.path(analysis_dir,'data')
knitr::opts_knit$set(root.dir = analysis_dir)
out_data_dir <- file.path(analysis_dir,'out')
if(!dir.exists(out_data_dir)) {dir.create(out_data_dir)}
```

**project folder:**  
`r analysis_dir`


## 1.2 functions
```{r limma toptable}
get_union_toptable <- function(fit3) {
  contrast_names  <-  colnames(coef(fit3))
  n_contrasts  <-  length(contrast_names)
  
  tt <-  foreach(i=1:n_contrasts, .combine=rbind) %do%
  { topTable(fit3, coef = i, 
             p.value = 1, number = Inf) %>% 
      mutate(GeneId=rownames(.), contrast=colnames(coef(fit3))[i]) }
  
  tt$contrast  <-  factor(tt$contrast, levels=contrast_names)
  return(tt)
}
```


```{r DE.limma trend}
DE.limma_trend<-function(Exp=Exp,CTRL,meta,best_DMSO=NULL,random_run=FALSE){
  if(!is.null(best_DMSO)){ 
    print('Starting DE calculations using best DMSO.')
    }else{print('Starting DE calculations.')
    }
  
  de<-lapply(1:length(Exp), function(i){
    b<-names(Exp)[i]
    meta_sub<- meta %>% filter(batch==b) %>% mutate(plate_barcode_short = substr(plate_barcode, nchar(plate_barcode)-2, nchar(plate_barcode)))
    if(!is.null(best_DMSO)) {
      meta_sub <- meta_sub %>% filter(treatment!=CTRL|barcode_well %in% best_DMSO$barcode_well) #only use best DMSO as control
    } 

    rownames(meta_sub)<-meta_sub$plate_id
    UMI_batch<-lapply(1:length(Exp[[i]]), function(j){
      #print(paste0('i ',i,' / j ',j))
      x<-Exp[[i]][[j]]
      mat<-x$UMI.counts
      mat<-mat[!rownames(mat) %in% grep("ERCC-",rownames(mat),value = T),]
      mat<-mat[order(row.names(mat)),]
      return(mat)
      })
    # active checking that the objects in the list have exactly the same names
    unames <- unique(unlist(lapply(UMI_batch, rownames)))
    stopifnot( all( sapply(UMI_batch, function(x) identical(rownames(x), unames)) ) )
    UMI_batch<-do.call(cbind,UMI_batch)


    UMI_batch<-UMI_batch[,meta_sub$plate_id]
    clean<-UMI_batch[apply(UMI_batch,1,max)>quantile(apply(UMI_batch,1,max),0.75),] 
    clean<-clean[,colSums(clean)>0] 

    d<-DGEList(counts=clean)
    d <- calcNormFactors(d, method="TMM")
    clean.TMM<-log2(edgeR::cpm(d,  normalized.lib.sizes=T,log=F)+1) 

    meta_sub<-meta_sub[colnames(clean.TMM),]
    meta_sub$Sample<-sapply(meta_sub$Sample, function(k) gsub("-",".",k))



    design<-model.matrix(~0+factor(meta_sub$Sample)+factor(meta_sub$replicate))
    colnames(design)<-c(levels(factor(meta_sub$Sample)),levels(factor(meta_sub$replicate))[-1])
    rownames(design)<-colnames(clean)
    samples<-unique(meta_sub$Sample)
    ctrl<-grep(CTRL,samples,value = T)
    #print(ctrl)
    samples<-samples[!samples %in% ctrl]

    contrasts<-sapply(samples, function(ctrs)paste0(ctrs,"-",ctrl))
    contrast.matrix<-limma::makeContrasts(contrasts=contrasts, levels = design)

    fit = limma::lmFit(clean.TMM, design)
    fit2 = limma::contrasts.fit(fit,contrast.matrix)
    fit3 = limma::eBayes(fit2,  trend = T)

    DE.table <- get_union_toptable(fit3) %>% 
    separate(contrast,c('contrast','ctrl_arm'),sep="-") %>% 
    select(-ctrl_arm) %>% 
    merge(meta_sub %>% 
            filter(!treatment ==CTRL) %>% 
            select(plate_barcode_short,treatment,treatment_dose,timepoint,Sample,plate_well,batch) %>% 
            distinct() %>% 
            group_by(treatment,treatment_dose,timepoint,Sample,batch) %>% 
            summarise(plate_well = paste(paste(plate_barcode_short,plate_well,sep = " "), collapse=",")),
          sort=FALSE, by.x='contrast',by.y='Sample') %>% mutate(Sample=contrast) # combine metadata with toptable
    
  })
  if (random_run==TRUE){
    de<-do.call(rbind,de) %>% 
      filter(Sample=="RC_to_SA") %>% 
      group_by(batch,plate_well) %>%
      filter(abs(logFC)>1,adj.P.Val<0.1) %>%
      summarise(count=n()) %>%
      mutate(run_no=n,contrast='RC_to_SA') %>% 
      ungroup() 
    }else{
    de<-do.call(rbind,de) 
    }
  return(de)
}
```

```{r volcano plot}
vpPlot_DElabel <- function(this_contrast_toptabel,batch_select=1,this_arms){
  
  pcut<-0.1
  #color= black,red, blue
  #        0     1      2   
  color_custum<-c(rgb(0,0,0,0.5),rgb(1,0,0,1),rgb(0,0,1,1))
  
  this_contrast_toptabel <- this_contrast_toptabel %>% 
    filter(treatment %in% this_arms,batch==batch_select) %>% 
    mutate(label=0)
  
  

  high_concentration<-this_contrast_toptabel %>% select(treatment_dose) %>% max() 
  
  this_contrast_toptabel_plot<-NULL

  for (SampleName_lib_temp in this_arms) { 
    upregulate_gene <- this_contrast_toptabel %>% 
      filter(treatment == SampleName_lib_temp) %>% 
      filter(treatment_dose==high_concentration, adj.P.Val<pcut, logFC>1) %>% 
      select(GeneId) %>% 
      .$GeneId
    downregulate_gene <-this_contrast_toptabel %>% 
    filter(treatment == SampleName_lib_temp) %>%
    filter(treatment_dose==high_concentration, adj.P.Val<pcut, logFC< -1) %>% 
    select(GeneId) %>% 
    .$GeneId

    this_contrast_toptabel_plot <- rbind(this_contrast_toptabel_plot,this_contrast_toptabel 
                                      %>%  filter(treatment==SampleName_lib_temp) %>% 
                                        mutate(label=ifelse(GeneId %in% upregulate_gene,1,label)) %>% 
                                        mutate(label=ifelse(GeneId %in% downregulate_gene,2,label)))
  }
  
  this_contrast_toptabel_plot$label<-as.factor(this_contrast_toptabel_plot$label)
  levels(this_contrast_toptabel_plot$label)<-c("not significant ","upregulated genes","downregulated genes")
  this_contrast_toptabel_plot$treatment<-factor(this_contrast_toptabel_plot$treatment)

 
  
  vp<-this_contrast_toptabel_plot %>% arrange(label) %>% 
    ggplot(aes(x=logFC, y=-log10(adj.P.Val), color=label))+
    scale_color_manual(values = color_custum)+
    geom_point(fill="white",shape=21, size=1, stroke=0.5) +
    geom_abline(slope = 0, intercept = -log10(pcut), size=0.3, linetype='dashed') +
    geom_vline(xintercept = -1, size=0.3, linetype='dashed') +
    geom_vline(xintercept = 1, size=0.3, linetype='dashed') +
    xlim(-8,8)+
    theme_bw() +
    theme(axis.text.x = element_text(face="bold",size=14),
          axis.text.y = element_text(face="bold", size=10),
          axis.title=element_text(size=14,face="bold"),
        legend.text=element_text(size=12) ) +
    facet_grid(treatment~treatment_dose)+
    theme(strip.text = element_text(face="bold", size=12))

  return(vp)
  }
```

```{r VennDiagram}
## works up to 3 groups comparison now
VD_plot <- function(this_contrast_toptable,batch_select=1){
  this_contrast_toptable_plot <- this_contrast_toptable %>% 
  mutate(sig=ifelse(abs(logFC)>1 & adj.P.Val<0.1,-1,0)) %>% 
    mutate(sig=ifelse(logFC>1 & adj.P.Val<0.1,1,sig)) %>%
    mutate(contrast=paste0(treatment_dose,'uM')) %>% 
    select(contrast,GeneId,sig) %>% 
    reshape2::dcast(GeneId~contrast,value.var="sig")
  
  
  rownames(this_contrast_toptable_plot) <- this_contrast_toptable_plot$GeneId
  return(this_contrast_toptable_plot %>% select(-GeneId) %>% vennDiagram(circle.col=c("turquoise", "salmon","palegreen"),cex=1))

}
```


```{r UMAP}
pca_umap <- function(counts=NULL,center_pca=T,metric="euclidean", scale_pca=T,n_neighbors=15,n_pca=20){
  
  pca<-prcomp(t(counts), scale = scale_pca, center = center_pca)
  rownames(pca$x)  <-  colnames(counts)
  umap  <-  umap(pca$x[,1:n_pca],method = "umap-learn",metric=metric, n_neighbors=n_neighbors)
  rownames(umap$layout)  <-  colnames(counts)
  return(umap)

  
}

```

```{r customized pair plot}
ggpairs_custom<-function(toptable_meta,this_arms,p_cut,corr_size=3,batch_s=1,strip_size=NULL,label_size=NULL,exclusive_gene=NULL){
  
  toptable_meta=toptable_meta %>% mutate(contrast=paste(treatment,treatment_dose,timepoint,sep="_"))
  this_contrast=toptable_meta %>% 
    filter(Sample %in% this_arms,batch==batch_s) %>% 
    arrange(treatment_dose) %>% 
    select(contrast) %>% 
    distinct() %>%.$contrast
  p_cut <- p_cut

  
if (is.null(exclusive_gene)) {
valid_genes <- toptable_meta %>% 
  filter(Sample %in% this_arms) %>%
  filter(batch==batch_s) %>%
  filter(adj.P.Val<p_cut) %>%
  .$GeneId %>%
  unique()
} else {
  
  valid_genes <- toptable_meta %>% 
    filter(Sample %in% this_arms) %>%
    filter(batch==batch_s) %>%
    filter(adj.P.Val<p_cut) %>%
  .$GeneId %>%
  unique() %>% 
    setdiff(exclusive_gene)
  
}

table_to_plot1<-toptable_meta %>% 
  filter(Sample %in% this_arms) %>%
  filter(batch==batch_s) %>%
  filter(GeneId %in% valid_genes) %>%
  dplyr::select(GeneId, contrast, logFC) %>%
  setDT %>%
  data.table::dcast(GeneId ~ contrast, value.var = 'logFC') %>%
  as.data.frame()

table_to_plot1<-table_to_plot1[,c("GeneId",this_contrast)]
rownames(table_to_plot1)<-table_to_plot1$GeneId

table_to_plot2<-toptable_meta %>% 
  filter(Sample %in% this_arms) %>%
  filter(batch==batch_s) %>%
  filter(adj.P.Val<p_cut) %>%
  dplyr::select(GeneId, contrast, logFC) %>%
  setDT %>%
  data.table::dcast(GeneId ~ contrast, value.var = 'logFC') %>%
  as.data.frame()

missing_col<-setdiff(colnames(table_to_plot1),colnames(table_to_plot2))
if (!identical(missing_col, character(0))) {
  missing_mat<-data.frame(matrix(0, nrow = nrow(table_to_plot2), ncol =as.numeric( length(missing_col))))
  missing_mat[missing_mat==0]=NA
  colnames(missing_mat)<-missing_col
  table_to_plot2<-cbind(table_to_plot2,missing_mat)
}

table_to_plot2<-table_to_plot2[,c("GeneId",this_contrast)]

data_plot<-inner_join(table_to_plot1,table_to_plot2,by="GeneId")
  
  

  rownames(data_plot)<-data_plot$GeneId
  data_plot<-data_plot %>% select(-"GeneId")
  
  axis_limt<-max(abs(data_plot),na.rm = TRUE)
  
  diagfun <- function(data,mapping){
    ggplot(data = data, mapping = mapping)+
      geom_density(color="darkblue", fill="lightblue") +
       scale_x_continuous(limits = c(-axis_limt, axis_limt)) 
      # scale_y_continuous(limits = c(-axis_limt, axis_limt))
    }
  
  corr_heatmap <- function(data, mapping, method="p", use="pairwise", ...){

              # grab data
              x <- eval_data_col(data, mapping$x)
              y <- eval_data_col(data, mapping$y)

              # calculate correlation
              corr <- cor(x, y, method=method, use=use)
              colFn <- colorRampPalette(c("blue", "white", "red"), interpolate ='spline')
              fill <- colFn(100)[findInterval(corr, seq(-1, 1, length=100))]
              ggally_cor(data = data, mapping = mapping, ...) + 
                theme_classic()+
                theme(panel.background = element_rect(fill=fill,colour = fill))
  }
  
  
  pm<-ggpairs(data_plot,c(1:as.numeric(length(colnames(data_plot))/2)),columnLabels=colnames(table_to_plot1)[-1],diag=list(continuous = wrap(diagfun)),
              upper = list(continuous = corr_heatmap),progress = F)+theme(axis.text = element_text(size = label_size),strip.placement = "outside", 
                                                                          text = element_text(size = strip_size) )
  
  method<-"pearson"
  pm2 <- pm
  color_custum<-c(rgb(0,0,0,0.5),rgb(0,1,0,0.7),rgb(0,0,1,0.7),rgb(1,0,0,1))
  label_list<-c('not significant','x axis DE genes','y axis DE genes','shared DE genes')
  for(i in 2:pm$nrow) {
       for(j in 1:(i-1)) {
         
         x <- GGally::eval_data_col(pm[i,j]$data, pm[i,j]$mapping$x)
         y <- GGally::eval_data_col(pm[i,j]$data, pm[i,j]$mapping$y)
         corr<- cor(x,y,method=method,use="na.or.complete")
         col_name_x_x<-paste0(gsub("\\.[^\\.]*$","",pm[i,j]$labels$x),".x")
         col_name_y_x<-paste0(gsub("\\.[^\\.]*$","",pm[i,j]$labels$y),".x")
         col_name_x_y<-paste0(gsub("\\.[^\\.]*$","",pm[i,j]$labels$x),".y")
         col_name_y_y<-paste0(gsub("\\.[^\\.]*$","",pm[i,j]$labels$y),".y")
         col_name<-c(col_name_x_x,col_name_y_x,col_name_x_y,col_name_y_y)
         data_sub<-pm$data[,col_name]
         
         data_sub<-data_sub %>% 
           mutate(label = ifelse(!is.na(!!sym(col_name_x_y)) & 
                                   abs(!!sym(col_name_x_y))>1,1,0)) %>%
          mutate(label = ifelse(!is.na(!!sym(col_name_y_y)) &
                                  abs(!!sym(col_name_y_y))>1,2,label)) %>%
          mutate(label = ifelse(!is.na(!!sym(col_name_x_y)) &
                        abs(!!sym(col_name_x_y))>1 &
                          !is.na(!!sym(col_name_y_y))&
                           abs(!!sym(col_name_y_y))>1 ,3,label)) %>% 
           arrange(label)
         
          unique_label<-sort(unique(data_sub$label))
          data_sub$label<-as.factor(data_sub$label)
          levels(data_sub$label)<-label_list[unique_label+1]
          
          p<-ggplot(data_sub,aes(x=!!sym(pm[i,j]$labels$x),y=!!sym(pm[i,j]$labels$y),color=label))+
               geom_point(size=2,shape=21,stroke=0.5,fill="white")+theme_bw()+scale_color_manual(values = color_custum[unique_label+1])+ scale_shape(solid = TRUE) +
            scale_x_continuous(limits = c(-axis_limt, axis_limt)) +
            scale_y_continuous(limits = c(-axis_limt, axis_limt)) +
            geom_abline(slope = 0, intercept = -1, size=0.3, linetype='dashed') +
            geom_abline(slope = 0, intercept =  1, size=0.3, linetype='dashed') +
            geom_vline(xintercept = -1, size=0.3, linetype='dashed') +
            geom_vline(xintercept = 1, size=0.3, linetype='dashed')
          pm2[i,j]=p+geom_label(data = data.frame(xlabel = -axis_limt,
                                          ylabel = max(axis_limt, na.rm = TRUE),
                                          lab = round(corr, digits = 3)),
                                mapping = ggplot2::aes(x = xlabel, y = ylabel, label = lab),
                                hjust = 0, vjust = 1,size = corr_size, fontface = "bold",
                          inherit.aes = FALSE # do not inherit anything from the ...
                          ) 
          
          
       }
   }
  return(pm2)
}




```


### UMI count table preparation
```{r count matrix,message = FALSE}
meta <- read.csv(file.path(input_data_dir,'meta.csv'),stringsAsFactors = F) %>% 
  filter(plate_barcode %in% c("VH02001612", "VH02001614", "VH02001618"))
Exp<-lapply(unique(meta$batch), function(x){
  b<-unique(meta[meta$batch==x,]$plate_barcode)
  res<-lapply(b, function(y){
    load(file.path(input_data_dir, paste0("flowcell_4000_UMI_decode_",y,".RData")),verbose=T)
    annot<-meta[meta$plate_barcode==y,]
    rownames(annot) <- apply( annot[ , c('plate_barcode','well_index') ] , 1 , paste , collapse = "_" )
    UMI_decode<-UMI_decode[!rownames(UMI_decode) %in% grep("ERCC-",rownames(UMI_decode),value = T),]
    UMI_annot<-list(UMI_decode,annot)
    names(UMI_annot)<-c("UMI.counts", "Annotation")
    return(UMI_annot)
  })
  names(res)<-b
  return(res)
})
names(Exp)<-unique(meta$batch)

save(Exp, file=file.path(out_data_dir,"Exp_Init.RData"),compress = TRUE)

```
```{r}
check_threads <- function() {
  cat("Hardware cores (logical/physical):",
      parallel::detectCores(TRUE), "/", parallel::detectCores(FALSE), "\n")
  cat("foreach backend/workers: ",
      foreach::getDoParName(), "/", foreach::getDoParWorkers(), "\n", sep = "")
  if (requireNamespace("future", quietly = TRUE)) {
    cat("future plan/workers: ", capture.output(future::plan()), "\n", sep = "")
    cat("future nbrOfWorkers: ", future::nbrOfWorkers(), "\n", sep = "")
  }
  if (requireNamespace("data.table", quietly = TRUE)) {
    cat("data.table threads: ", data.table::getDTthreads(), "\n", sep = "")
  }
  if (requireNamespace("RhpcBLASctl", quietly = TRUE)) {
    cat("BLAS threads: ", RhpcBLASctl::blas_get_num_procs(), "\n", sep = "")
    cat("OMP max threads: ", RhpcBLASctl::omp_get_max_threads(), "\n", sep = "")
  } else {
    envs <- Sys.getenv(c("OPENBLAS_NUM_THREADS","MKL_NUM_THREADS","OMP_NUM_THREADS","VECLIB_MAXIMUM_THREADS"))
    cat("BLAS/OMP env vars:\n"); print(envs[envs != ""])
  }
}
check_threads()

```


# 2 Step1
## 2.1 run first 500 random run
```{r run using foreach, message=FALSE}

step1_func <- function(n){
  
  CTRL="DMSO"
  rand_runs=TRUE
  
  meta <- read.csv(file.path(input_data_dir,'meta.csv'),stringsAsFactors = F) %>%  
    mutate(replicate=paste0('rep',plate_replicate),plate_id=paste0(plate_barcode,"_",well_index)) %>%
    filter(plate_barcode %in% c("VH02001612", "VH02001614", "VH02001618"))
  load(file.path(out_data_dir, 'Exp_Init.RData'),verbose = T)
  
  DMSO_sample <- meta %>% filter(treatment==CTRL) %>% select(batch,plate_barcode,plate_well) %>%
    group_by(plate_barcode) %>% 
    do(sample_n(.,1)) %>% 
    mutate(Sample="RC_to_SA",treatment="RC_to_SA")  


  meta <- meta %>% left_join(DMSO_sample,by=c('batch','plate_barcode','plate_well'),suffix=c("","_randR")) %>%
    mutate(Sample=ifelse(is.na(Sample_randR),Sample,Sample_randR)) %>% 
    mutate(treatment=ifelse(is.na(treatment_randR),treatment,treatment_randR))
  
  DE<-DE.limma_trend(Exp=Exp,CTRL=CTRL,meta=meta,random_run =rand_runs)
}
# DE_count_500 <- foreach(n=1:10,.packages=c("dplyr","limma","tidyr","foreach","edgeR"),.combine=rbind) %do% step1_func(n)

```

```{r, message=FALSE, warning=FALSE,results='hide'}
options(dplyr.summarise.inform = FALSE)
# ---- helper to pretty print seconds ----
fmt_secs <- function(x) {
  if (is.na(x)) return("NA")
  if (x < 60) return(sprintf("%.2fs", x))
  if (x < 3600) return(sprintf("%dm %.1fs", floor(x/60), x %% 60))
  sprintf("%dh %dm %.0fs", floor(x/3600), floor((x%%3600)/60), x%%60)
}

iters <- 1:50

# ---- total wall time + per-iteration timings ----
# total_tm <- system.time({
#   # return a list of {data, iter, seconds} per iteration
#   lst <- foreach(
#     n = iters,
#     .packages = c("dplyr","limma","tidyr","foreach","edgeR"),
#     .combine  = "c"     # concatenate list-of-lists
#   ) %do% {
#     t0  <- proc.time()[["elapsed"]]
#     res <- step1_func(n)
#     dt  <- proc.time()[["elapsed"]] - t0
#     list(list(data = res, iter = n, seconds = dt))
#   }
# })

# extract results and timings
# iter_times <- vapply(lst, function(x) x$seconds, numeric(1))
# DE_count_500 <- dplyr::bind_rows(lapply(lst, function(x) x$data))



```

<!-- # ```{r} -->
<!-- #  -->
<!-- # # ---- report ---- -->
<!-- # # cat("\n=== Runtime report ===\n") -->
<!-- # # cat("Total elapsed: ", fmt_secs(unname(total_tm["elapsed"])), "\n", sep = "") -->
<!-- # # cat(sprintf("Per-iteration (median [IQR]): %.2fs [%.2f–%.2f]\n", -->
<!-- # #             median(iter_times, na.rm = TRUE), -->
<!-- # #             quantile(iter_times, 0.25, na.rm = TRUE), -->
<!-- # #             quantile(iter_times, 0.75, na.rm = TRUE))) -->
<!-- # #  -->
<!-- # # print(total_tm) -->
<!-- #  -->
<!-- # # Optional: print each iteration’s time -->
<!-- # # print(data.frame(iter = iters, seconds = round(iter_times, 3))) -->
<!-- #  -->
<!-- # # Optional: save a CSV next to your outputs -->
<!-- # # readr::write_csv(data.frame(iter = iters, seconds = iter_times), -->
<!-- # #                  file.path(out_data_dir, "DE_count_500_iter_times.csv")) -->
<!-- #  -->
<!-- #  -->
<!-- #  -->
<!-- #  -->
<!-- #  -->
<!-- # ``` -->


```{r, message=FALSE, warning=FALSE,results='hide'}

# ---- RAM usage ----
# remotes::install_github("tpq/peakRAM")
library(peakRAM)
res1 <- peakRAM({
  DE_count_500 <- foreach(n = iters,
                          .packages = c("dplyr","limma","tidyr","foreach","edgeR"),
                          .combine  = rbind) %do% step1_func(n)
})

res2 <- peakRAM({
  DE_count_500 <- foreach(n = iters,
                          .packages = c("dplyr","limma","tidyr","foreach","edgeR"),
                          .combine  = rbind) %do% step1_func(n)
})

res3 <- peakRAM({
  DE_count_500 <- foreach(n = iters,
                          .packages = c("dplyr","limma","tidyr","foreach","edgeR"),
                          .combine  = rbind) %do% step1_func(n)
})
```


```{r}
res1

res2

res3
```




```{r, message=FALSE, warning=FALSE,results='hide'}
if (!requireNamespace("ps", quietly = TRUE)) install.packages("ps")
get_rss_mb <- function() ps::ps_memory_info(ps::ps_handle())[1] / 1024^2

rss_before <- get_rss_mb()
tm1 <- system.time({
  DE_count_500 <- foreach(n = iters,
                          .packages = c("dplyr","limma","tidyr","edgeR"),
                          .combine  = rbind) %do% step1_func(n)
})
rss_after  <- get_rss_mb()
cat(sprintf("Elapsed: %.1fs | RSS before→after: %.0f→%.0f MiB (Δ %.0f MiB)\n",
            tm1["elapsed"], rss_before, rss_after, rss_after - rss_before))


```

```{r}
tm1

```


```{r, message=FALSE, warning=FALSE,results='hide'}
if (!requireNamespace("ps", quietly = TRUE)) install.packages("ps")
get_rss_mb <- function() ps::ps_memory_info(ps::ps_handle())[1] / 1024^2

rss_before <- get_rss_mb()
tm2 <- system.time({
  DE_count_500 <- foreach(n = iters,
                          .packages = c("dplyr","limma","tidyr","edgeR"),
                          .combine  = rbind) %do% step1_func(n)
})
rss_after  <- get_rss_mb()
cat(sprintf("Elapsed: %.1fs | RSS before→after: %.0f→%.0f MiB (Δ %.0f MiB)\n",
            tm2["elapsed"], rss_before, rss_after, rss_after - rss_before))


```

```{r}
tm2

```


```{r, message=FALSE, warning=FALSE,results='hide'}
if (!requireNamespace("ps", quietly = TRUE)) install.packages("ps")
get_rss_mb <- function() ps::ps_memory_info(ps::ps_handle())[1] / 1024^2

rss_before <- get_rss_mb()
tm3 <- system.time({
  DE_count_500 <- foreach(n = iters,
                          .packages = c("dplyr","limma","tidyr","edgeR"),
                          .combine  = rbind) %do% step1_func(n)
})
rss_after  <- get_rss_mb()
cat(sprintf("Elapsed: %.1fs | RSS before→after: %.0f→%.0f MiB (Δ %.0f MiB)\n",
            tm3["elapsed"], rss_before, rss_after, rss_after - rss_before))


```

```{r}
tm3

```

