name: Build a docker image of R packages for macpie

on:
  push:
    branches:
      - 'main'
    paths:
      - 'dockers/**'  
      - '.github/workflows/docker_image.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./dockers
          tags: xliu81/macpie:v1.0.0
          file: ./dockers/Dockerfile
