name: Build and Deploy pkgdown Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Install required packages and build pkgdown site (skip articles, as macpie.html is rendered)
        run: |
          Rscript -e "install.packages('pkgdown', repos='https://cloud.r-project.org')"
          Rscript -e "pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)"
        shell: Rscript{0}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs


