name: Build and Deploy pkgdown Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install required packages and build pkgdown site
        run: |
          Rscript -e "install.packages(c('pkgdown','devtools'), repos='https://cloud.r-project.org')"
          Rscript -e "pkgdown::build_site()"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs


