# .github/workflows/r-cmd-check.yaml
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples

on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-latest,   r: 'release' }
          - { os: windows-latest, r: 'release' }
          - { os: ubuntu-latest,  r: 'devel',    http-user-agent: 'release' }
          - { os: ubuntu-latest,  r: 'release' }
          - { os: ubuntu-latest,  r: 'oldrel-1' }

    env:
      GITHUB_PAT:     ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version:        ${{ matrix.config.r }}
          http-user-agent:  ${{ matrix.config.http-user-agent }}
          use-public-rspm:  true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          # R CMD check flags:
          args:       '--no-manual --as-cran --ignore-vignettes'
          # R CMD build flags:
          build_args: '--no-build-vignettes'
