# .github/workflows/r-cmd-check.yaml
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples

on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-latest,   r: 'release' }
          - { os: windows-latest, r: 'release' }
          - { os: ubuntu-latest,  r: 'devel',    http-user-agent: 'release' }
          - { os: ubuntu-latest,  r: 'release' }
          - { os: ubuntu-latest,  r: 'oldrel-1' }

    env:
      GITHUB_PAT:     ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version:        ${{ matrix.config.r }}
          http-user-agent:  ${{ matrix.config.http-user-agent }}
          use-public-rspm:  true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      # NEW: Install system Java & other lib dependencies for Ubuntu
      - name: Install Java & system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk libcurl4-openssl-dev libxml2-dev libssl-dev

      # NEW: Install R package dependencies: rJava, rcdklibs, rcdk
      - name: Install R package dependencies
        run: |
          Rscript -e 'install.packages(c("rJava", "rcdklibs", "rcdk"), repos="https://packagemanager.rstudio.com/all/latest")'

      # NEW: Print current Java config
      - name: Check Java and R linkage
        if: runner.os == 'Linux'
        run: |
          java -version
          Rscript -e 'library(rJava); .jinit(); cat("Java version in R:", .jcall("java/lang/System", "S", "getProperty", "java.version"), "\n")'

      # Skip javareconf on Windows
      - name: Check Java and R linkage (Windows - skip javareconf)
        if: runner.os == 'Windows'
        run: |
          java -version
          echo "Skipping R CMD javareconf on Windows"

      # NEW: Run test
      - name: Run test
        run: |
          Rscript -e 'library(rcdk); parse.smiles("COO")'	

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          # R CMD check flags:
          args:  'c("--as-cran", "--ignore-vignettes", "--no-manual", "--no-vignettes")'
          # flags for R CMD build:
          build_args: 'c("--no-build-vignettes", "--no-manual")'
